### ISSUE TITLE
Links to Tier descriptions in table on "In-Depth Overview" page broken

### ISSUE THREAD

**Issue by ifreund** [ziglang/www.ziglang.org#100]
They currently link to `https://ziglang.org/#Tier-1-Support` which I suppose should be `https://ziglang.org/learn/overview/#Tier-1-Support`.

**Comment by kristoff-it** [comment]
Thanks I'll fix this as soon as we merge the pending translation PRs.

**Comment by nektro** [comment]
This was changed again and the support tables are now only going to be kept up to date in the release notes

additionally it is not possible to redirect based on the hash of a url without client side js since it is not sent to the server

**Comment by jgollenz** [comment]
> This was changed again and the support tables are now only going to be kept up to date in the release notes

So where should all those links point to? Maybe just down to `#wide-range-of-targets-supported`?

**Comment by nektro** [comment]
here https://ziglang.org/download/0.8.1/release-notes.html#Tier-1-Support

**Comment by jgollenz** [comment]
@nektro when I make a PR, do I fix one file that then gets translated into the target languages or do I have to fix the links in each translated .md file? Probably the latter, right?
