### ISSUE TITLE
Grammatical error in footer of home page

### ISSUE THREAD

**Issue by CoolDeveloper101** [ziglang/www.ziglang.org#112]
I am not sure what was meant to be written in the footer but this doesn't feel right.
![image](https://user-images.githubusercontent.com/49064764/106381451-d3121800-63de-11eb-87e1-bbc63bbe3b86.png)

**Comment by kristoff-it** [comment]
You will probably find other parts of the Zig project that might be confusing at first, make sure to always question if that's really the case and ask clarifications, like you're doing now!

Searching the phrase on google reveals the answer to your question, but apparently it's now the 20th anniversary of the meme, so here's a link for your convenience, enjoy!

https://www.theverge.com/2021/2/17/22287208/all-your-base-are-belong-to-us-20th-anniversary-internet-culture
