### ISSUE TITLE
Add hello world example to samples page

### ISSUE THREAD

**Issue by leighmcculloch** [ziglang/www.ziglang.org#117]
The learn samples showcase some advanced features and concerns like memory leaks, but as a someone who is new to Zig the first thing I need to see is hello world. i.e. The minimal application that runs and gives me some sense of where the entry point is and how to log so I can debug using some basic principles.

I think it would be helpful to add a hello world example to the samples page here:
https://ziglang.org/learn/samples/

I'd be happy to help with a PR, but I see there are many languages and I'd only be able to contribute English. I'm happy to do that if that'd be welcomed.

**Comment by kristoff-it** [comment]
The Getting Started guide shows you how to get to a hello world application, but regardless I  would happily accept a PR to add that example in the samples section!
