### ISSUE TITLE
text in some highlighted code examples is invisible

### ISSUE THREAD

**Issue by ikea-shark-official** [ziglang/www.ziglang.org#119]
there are some code examples where the syntax highlighting makes the code that's not supposed to be highlighted invisible

this only occurs in some highlighted code blocks

this error occurs in firefox, chromium, and gnome web

example instances I've seen of this:

on [https://ziglang.org/learn/getting-started]():
![image](https://user-images.githubusercontent.com/47906531/109718611-2b1e7480-7b6d-11eb-87ab-3e219ee26733.png)
![image](https://user-images.githubusercontent.com/47906531/109718682-3b365400-7b6d-11eb-92f2-b79886503d91.png)

on [https://ziglang.org/learn/why_zig_rust_d_cpp/]():
![image](https://user-images.githubusercontent.com/47906531/109718772-543f0500-7b6d-11eb-9150-82cba02f72d5.png)

**Comment by ketzu** [comment]
Same problem on Firefox, Chrome and Chromium Edge. (Also on IE11)

**Comment by kristoff-it** [comment]
Fixed in 400dff16fd77a73ee63f07384b35b004f476b3ea
