### ISSUE TITLE
I searched for allocators in the docs and didn't find it

### ISSUE THREAD

**Issue by lerno** [ziglang/www.ziglang.org#12]
There is no real information about how the allocators work.

**Comment by andrewrk** [comment]
Good point. I'll add this to the documentation shortlist.

**Comment by gunnarahlberg** [comment]
I suggest this can be closed, the https://ziglang.org/documentation/master/#toc-Memory works for me :)

**Comment by andrewrk** [comment]
Also https://ziglang.org/documentation/master/#Choosing-an-Allocator
