### ISSUE TITLE
Link to source code from package documentation

### ISSUE THREAD

**Issue by ROGERSM94** [ziglang/www.ziglang.org#121]
Some parts of the standard library documentation are lacking descriptions, for example [AutoHashMap](https://ziglang.org/documentation/master/std/#std;AutoHashMap) doesn't have a description for what its intended purpose/usage is (which may not be obvious to newer users).  But a quick link to the source code would show that it's a convenience wrapper over HashMap.

I think a nice convenience to help deal with these kinds of situations would be to link to the source code at the top of the page similar to how the Python documentation does it (example [here](https://docs.python.org/3.9/library/string.html#module-string).).

**Comment by kristoff-it** [comment]
Development of autogenerated docs is blocked until the selfhosted compiler is completed. I'm closing this issue because everything will go under a pretty heavy redesign anyway.
