### ISSUE TITLE
Question regarding statement in documentation

### ISSUE THREAD

**Issue by poldi1405** [ziglang/www.ziglang.org#128]
In [the documentation](https://ziglang.org/learn/overview/#small-simple-language) it is stated

> […] Go have throw/catch exceptions, so foo() might throw an exception, and prevent bar() from being called.

To my knowledge, it does not. What is this referring to? The only two things I can think of are:
- `panic()` which is a program exit due to a critical failure
- errors and their values

Regarding `panic()` there is the infrequently used `recover()` but dare I say that panic-recover is not throwing/catching an exception since it's rather a way of "emergency-stopping" a program.

So my question would be: is this a mistake in the documentation, my understanding, or something completely different maybe?

**Comment by mikdusan** [comment]
from https://blog.golang.org/defer-panic-and-recover

>For a real-world example of panic and recover, see the json package from the Go standard library. It encodes an interface with a set of recursive functions. If an error occurs when traversing the value, panic is called to unwind the stack to the top-level function call, which recovers from the panic and returns an appropriate error value (see the 'error' and 'marshal' methods of the encodeState type in encode.go).

- panic is induced
- normal control flow and error handling is dis-engaged
- returns and error-checking code no longer applies
- after an amount of unwinding some code decides to `recover` and re-engages normal control flow with an error

Isn't this exception handling, without an exception value, but exception handling nonetheless? What does _go_ do to prevent abusing this? It seems to me the cited example of "how" to use it is an abuse example.

Have things changed since this '2010 article? I have no clue.

**Comment by poldi1405** [comment]
> Isn't this exception handling

IMHO it is not. Panic differs in so far, that it is usually intended to bring a program to a halt.

To quote the [Go-Blog](https://blog.golang.org/defer-panic-and-recover)
> execution of F stops, any deferred functions in F are executed normally, and then F returns to its caller. To the caller, F then behaves like a call to panic

> What does go do to prevent abusing this?

The language itself does nothing against it. How is an algorithm supposed to distinguish abuse from an unusual use-case?

> It seems to me the cited example of "how" to use it is an abuse example.

The example shown is obviously intended to show how panic and recover are working. Whether someone new to the language would know that, I can not say. When reading the communities stance (Reddit, GitHub, StackOverflow, Medium, …) the usual recommendation is: "don't panic [unless you have good reason]"

> Have things changed since this '2010 article? I have no clue.

To my knowledge, no changes have been made to the inner workings of panic.

**Comment by mikdusan** [comment]
> IMHO it is not. Panic differs in so far, that it is usually intended to bring a program to a halt.

How do you reconcile that statement with cited example using panic to return an error value from json marshalling function?

| The example shown is obviously intended to show how panic and recover are working.

Right. So me, being a novice go user sees the blog, sees the idiomatic example and concludes... oh an out-of-band error mechanism.

from https://en.wikipedia.org/wiki/Exception_handling

> Go was initially released with exception handling explicitly omitted, with the developers arguing that it obfuscated control flow. Later, the exception-like panic/recover mechanism was added to the language, which the Go authors advise using only for unrecoverable errors that should halt the entire process.

json does not halt. It re-engages with regular control flow and returns an error.

**Comment by poldi1405** [comment]
> How do you reconcile that statement with cited example using panic/recover to return an error value from json marshalling function?

In this case I'd call it a very strange way of signalling. And I am also perfectly on board with saying that the json package should not panic internally. And as far as I can see, it now only uses panic on unrecoverable errors.

I assume that the `recovery()` part would be your "catch" function. Using recovery is an asset IMHO because it allows things like [this](https://git.sr.ht/~poldi1405/glog/tree/master/recover.go#L14) which basically allows writing a panic to a log so it can be examined and fixed.

**Comment by poldi1405** [comment]
A core difference would also be that `recover()` is not reusable and only executed when the function returns. It does not restore control flow. see [here](https://play.golang.org/p/YmI--Xm-8mj) where the second statement is never reached.

**Comment by mikdusan** [comment]
>A core difference would also be that recover() is not reusable and only executed when the function returns. It does not restore control flow.

see the following snippet where control flow is restored:

https://github.com/golang/go/blob/f5423ea615b94455e4f6b9cbee491b492bf2e1fe/src/encoding/json/encode.go#L322-L334

and this from the blog:

>If the current goroutine is panicking, a call to recover will capture the value given to panic and resume normal execution.

specifically "resume normal execution"

**Comment by poldi1405** [comment]
> see the following snippet where control flow is restored:

The control flow is not restored. The return value is replaced if it is a jsonError and the panicking is aborted. Otherwise the panic is forwarded.

**Comment by poldi1405** [comment]
> edit: oh you linked a go playground; try this one: https://play.golang.org/p/B9VSTUsHud__V

I would say the control flow remains untouched since the execution of middleman is aborted. It's similar to returning another value indicating a panic

**Comment by andrewrk** [comment]
Website is correct. Panic/recover in go is exceptions.
