### ISSUE TITLE
Download page could be clearer about what to do with the unzipped contents

### ISSUE THREAD

**Issue by canadaduane** [ziglang/www.ziglang.org#137]
First time Zig user here.

I downloaded Zig after visiting https://ziglang.org/download/ and it's really nice to see a small, clean package that includes offline docs.

However, I would have appreciated a little more instruction on what the constraints are with regard to the package contents:

- where should this folder live? Any "best practices"?
- must the 'zig' runtime be kept in a folder that sits alongside the 'lib' folder?

I ended up moving the entire contents to `~/.zig` and adding "$HOME/.zig" to my path. I'm not sure if this is the best approach, but it seemed to work. Hopefully it won't bite me later.

**Comment by kristoff-it** [comment]
From the front page and from the Learn section you can access a Getting Started guide with some information on how to use the archives and other alternative installation methods. The idea is that power users can just download an archive and be done with it, while people that need more guidance can consult the guide. Perhaps the first line in the Downloads page should link to that.

**Comment by canadaduane** [comment]
> Perhaps the first line in the Downloads page should link to that.

I like it. I was looking for a link to something like that.
