### ISSUE TITLE
I searched for the standard library in the docs and didn't find it

### ISSUE THREAD

**Issue by lerno** [ziglang/www.ziglang.org#14]
There is currently nothing about the standard library in the docs. Even though this might be a moving target, it would be helpful to have at least a list of different modules and what functionality they cover + an overview of very common library functions (the available allocators, string functions, IO) just so you can get up and running writing a test program to feel the language out without reading through the library files. Bonus points for having the entire standard library docs automatically generated from the source code.

**Comment by kristoff-it** [comment]
The docs for the standard library will live in a separate section once the autodoc tool is complete enough (see the `-femit-docs` option in the zig compiler). We're waiting for the self-hosted compiler to be complete enough so that we can port the current autodoc code to it.
