### ISSUE TITLE
In documentation, style breadcrumbs navigation to look less like tabs

### ISSUE THREAD

**Issue by roryokane** [ziglang/www.ziglang.org#148]
## Problem

I used the documentation at https://ziglang.org/documentation/master/std/ on two previous days. Both days, I failed to understand what this section with the orange rectangle was supposed to mean:

<img width="362" alt="confusing breadcrumbs in Zig docs" src="https://user-images.githubusercontent.com/79168/132971997-b06b2919-fc50-4b17-a44b-c514a6b4ca97.png">

(The example page is [unicode.Utf8View (Struct)](https://ziglang.org/documentation/master/std/#std;unicode.Utf8View). That confusing section in context:)

<img width="560" alt="confusing breadcrumbs in context of Zig docs" src="https://user-images.githubusercontent.com/79168/132972002-3d3692f8-f125-4019-bca6-1cdbab4d4d49.png">

On all the pages I noticed that list on, I recognized that the orange rectangle part (e.g. “Utf8View”) was the current page, but didn’t understand the meaning of the previous parts. My best guess was that it was a list of open tabs. I thought “I don’t remember opening any tabs… I guess it opens tabs for me automatically based on my history. Yet I don’t remember visiting pages named “std” or “unicode”… well, whatever. Let me just read the documentation I searched for.”

It was only today that I realized that those aren’t supposed to be tabs – they are supposed to show the hierarchy of the current type. In other words, they are [breadcrumbs](https://en.wikipedia.org/wiki/Breadcrumb_navigation). (I realized that after finding [std.mem.split](https://ziglang.org/documentation/master/std/#std;mem.split) – I think the shortness of that name helped me recognize the fully-qualified name in the breadcrumbs more easily.)

Search keywords: the navigation section’s HTML has `id`s `sectNav` and `listNav`.

## Ideas for solutions

I think the styling of those breadcrumbs could make their purpose clearer. Some ideas:

-   Put ‘>’ between the segments.

    ```
    std    >    unicode    >    Utf8View
    ```

-   Put only textual dots between the segments. [Rust’s documentation](https://doc.rust-lang.org/std/char/fn.from_u32.html) uses styling somewhat similar to this.

    ```
    std.unicode.Utf8View
    ```

-   Put dots between the segments with a bit of extra spacing to suggest that each part is clickable.

    ```
    std . unicode . Utf8View
    ```

-   Turn the rectangles into chevron shapes. It would look something like this:

    ```
    ❯    std    ❯    unicode    ❯    Utf8View    ❯
    ```

**Comment by nektro** [comment]
Please read the warning at the top of the page.

**Comment by roryokane** [comment]
This warning?

> These docs are experimental. [Progress depends on the self-hosted compiler](https://kristoff.it/blog/zig-new-relationship-llvm/), [consider reading the stdlib source in the meantime](https://github.com/ziglang/zig/wiki/How-to-read-the-standard-library-source-code).

I had already read that. I’m not sure what you mean.

Are you trying to suggest that it’s useless to leave feedback about the docs because they’re not finished yet? I don’t think that follows. The docs website, though unfinished, has benefits over reading the source code – for example, it’s easier to use on mobile. Thus, improving the docs website would help people who use it now for those benefits.

Even if nobody is interested in changing the docs website until the self-hosted compiler is better, I think it’s worth noting this UX improvement so that it isn’t missed when that time comes. I wouldn’t want the brand-new, fancy docs website to unthinkingly carry over the current website’s breadcrumb design.

**Comment by kristoff-it** [comment]
autodoc development should be discussed in the main zig repo as it's a component of the compiler itself, closing
