### ISSUE TITLE
Make release dates more recognizeable on the Download (Releases) page

### ISSUE THREAD

**Issue by roryokane** [ziglang/www.ziglang.org#150]
## Problem

I had been curious about release dates when browsing Zig’s website before, but hadn’t found them. Though I mainly looked at release notes pages (#149), I also had visited https://ziglang.org/download/ before, and hadn’t noticed the dates on that page. I only found they were on that page when I searched this repo for information about release dates and saw that they were inserted onto this page.

How a release on that page looks:

> <img width="426" alt="hard-to-see date on download page" src="https://user-images.githubusercontent.com/79168/132994864-cfa15ae8-9f83-47e5-a964-f4e17b94733c.png">

There are three factors making that release date hard to see:

- All the other items in that list are reference links. Those links are only there to be clicked on; there is no information to be gained by reading their text. When skimming, one might assume the first bullet point is the same.
- The date has no label. It doesn’t say it’s a release date; that has to be inferred from context.
- The date blends in with the release version number, which is repeated many times on that page (in every download link).

## Ideas for solutions

> <img width="430" alt="release date on download page 3 – expanded bullet point “Released on”" src="https://user-images.githubusercontent.com/79168/132995168-b8cad709-b449-47ac-ba6d-067fc4fcb69b.png">

> <img width="429" alt="release date on download page 2 – date in header as phrase “…, released …”" src="https://user-images.githubusercontent.com/79168/132995169-7bd96493-dfe4-4ec8-9729-3584186398fe.png">

> <img width="426" alt="release date on download page – small date in header “…, (released …)”" src="https://user-images.githubusercontent.com/79168/132995170-6ef510c6-4528-493f-963e-d45497f964a8.png">

I think I prefer the second one. Even the first one would be an improvement, though.

### Idea for the future

It also might be nice if “master” labeled the date differently, since it will have many release dates over time. It might call the date “Last released” or “Last updated” instead of “Released”. However, it looks like the code for the downloads page doesn’t output the master release separately:

https://github.com/ziglang/www.ziglang.org/blob/9de50d6ace53ac93106ced15073daf2c8691a612/config.toml#L11-L14

so let’s leave differentiating “master” for a later step.

## Implementation

https://ziglang.org/download/ is generated from this code that displays each release’s date from [data/releases.json](https://github.com/ziglang/www.ziglang.org/blob/master/data/releases.json) as a list item:

https://github.com/ziglang/www.ziglang.org/blob/9de50d6ace53ac93106ced15073daf2c8691a612/themes/ziglang-original/layouts/_default/downloads.html#L11-L16

That is the code to change.

In one of my above mockups, CSS would also need to be added somewhere to style a `span` in the heading to have smaller text: `font-size: 0.75em;`.

**Comment by nektro** [comment]
Please see my comment on #149

**Comment by kristoff-it** [comment]
Doesn't seem that people care too much about the discoverability of the date, as there was no other mention of this in the last couple of years, leaving things as they are since the information in fact is already pretty accessible even if not highlighted.
