### ISSUE TITLE
Grammar error and unclear intent in footer quote

### ISSUE THREAD

**Issue by jorisgeer** [ziglang/www.ziglang.org#152]
The home page shows this footer quote :

"All your codebase are belong to us."

It is gramtically incorrect, and I am not sure if visitors understand what is meant. It appears like a joke, but not one that relates to Zig in any good way.

**Comment by nektro** [comment]
It's from https://hero.fandom.com/wiki/ZIG_(Zero_Wing)

**Comment by jorisgeer** [comment]
People like me who do not know this game character may find it confusing or even offensive. If a substantial percentage of visitors to the site don't have this background, it may not benefit the site from having this quote,

**Comment by nektro** [comment]
It doesn't have any benefit. It's a harmless joke that gets immediately deleted once people start to write their own code.

**Comment by kristoff-it** [comment]
> People like me who do not know this game character may find it confusing or even offensive. If a substantial percentage of visitors to the site don't have this background, it may not benefit the site from having this quote,

That's a fair point, we'll consider removing the reference when developers won't be anymore the target audience oft the website.
