### ISSUE TITLE
Closed

### ISSUE THREAD

**Issue by PerryCodes** [ziglang/www.ziglang.org#156]

**Comment by andrewrk** [comment]
I don't mean to antagonize, but one thing to consider @PerryCodes is that the bug reporting form was there to help you. For example, it said **steps to reproduce**, and this is where you should have put copy this file into test.zig and then run `zig test foo.zig`.

Then it said **actual output**, which is where you would have pasted the program's output.

Then it said **expected output**, which is where you would have corrected the supposed error, however at this step you would have found no error, thus preventing yourself from being embarrassed.

The bug reporting form is there to help you.

Also yes this does have to do with the website, not the compiler.
