### ISSUE TITLE
Resources for Allocator Implementation

### ISSUE THREAD

**Issue by jgollenz** [ziglang/www.ziglang.org#166]
[Here](https://ziglang.org/documentation/master/#Implementing-an-Allocator) `std/mem.zig` and `std/heap.zig` are mentioned. 

1) They don't conform with the formatting of `std.builtin.zig` [here](https://ziglang.org/documentation/master/#panic)
2) I think it doesn't hurt to link to the actual files, since the section is already quite short

edit: formatting

**Comment by nektro** [comment]
1. not sure what you mean by this point
2. fair

**Comment by jgollenz** [comment]
1. Sorry, not `std.builtin.zig` but `std/builtin.zig`. It is formatted in index.html: `<code><span class="line">std/builtin.zig</span></code>` whereas `std/heap.zig` and `std/mem.zig` are plain text
