### ISSUE TITLE
Generic Data Structures could use an example showing referencing

### ISSUE THREAD

**Issue by trashhalo** [ziglang/www.ziglang.org#181]
Reading this section of the documentation https://ziglang.org/documentation/master/#toc-Generic-Data-Structures it was not clear to me that I could use these types in other types. I made a little test zig file to see if it would work and it does. https://gist.github.com/trashhalo/97fc90021759fdd1a134755963ac470f

It might be helpful in rounding out peoples understanding of these comptime types to show they can be used like other builtin types when building larger structures.

**Comment by kristoff-it** [comment]
While I agree that more extensive examples can be useful, the language reference is mainly designed to present the language in a complete but succinct way.

You might want to refer to Zig Learn or other similar resources which are designed to guide the learning process more directly.
