### ISSUE TITLE
Link to latest master build

### ISSUE THREAD

**Issue by leecannon** [ziglang/www.ziglang.org#201]
It would be nice if ziglang.org provided a direct link to the latest master, making [https://zigbin.io/master](https://zigbin.io/master) unnecessary.

**Comment by nektro** [comment]
the proper behavior is to parse https://ziglang.org/download/index.json

**Comment by nektro** [comment]
can't find the issue but this has been brought up before and it not efficiently possible on s3. it would also break the caching of the site and regularly degrade performance of the cdn

**Comment by kristoff-it** [comment]
If you really want a convenient way to get lastest zig, you should clone the repo and build it yourself. Since the time this discusson was created, it's become pretty easy to bootstrap Zig. Closing.
