### ISSUE TITLE
`Access-Control-Allow-Origin: *` removed from `index.json`

### ISSUE THREAD

**Issue by nektro** [ziglang/www.ziglang.org#208]
this is vital when making web requests to https://ziglang.org/download/index.json due to [Cross-Origin Resource Sharing rules](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

![image](https://user-images.githubusercontent.com/5464072/178091687-6966feaa-7d81-4a28-9ee9-c458d846fafd.png)

**Comment by kristoff-it** [comment]
Is this still necessary? Can you explain the usecase a little bit more?

**Comment by nektro** [comment]
> Is this still necessary? 

is the header still missing? yes
is this still needed? im not sure

> Can you explain the usecase a little bit more?

i dont remember what i was working on but the lack of this header makes `index.json` unable to be accessed from other websites in a browser through `fetch()` or `XMLHTTPRequest`. native/cli tools do not implement this cross-origin restriction

eg if i was on `nektro.net` i cannot `fetch('https://ziglang.org/download/index.json')` since that page is not a subresource of `ziglang.org`.

**Comment by andrewrk** [comment]
I don't want to have to care about adding this header, sorry
