### ISSUE TITLE
Incorrect info about other languages in "why zig" comparison. 

### ISSUE THREAD

**Issue by harrisonmetz** [ziglang/www.ziglang.org#209]
In the "why zig", it mentions hidden control flow and give a couple examples. One of the examples is about exceptions:

https://github.com/ziglang/www.ziglang.org/blob/2dfd906a40426fd06983ee866df9c49ca21c9181/content/learn/why_zig_rust_d_cpp.en.md?plain=1#L22

c++ does have exceptions (I don't know about D) but **Go lang certainly does not**. https://go.dev/blog/error-handling-and-go

I'm not sure if another language was meant to be used (certainly not Rust either as it doesn't have exceptions either), but just wanted to bring this up. I can't correct it because I don't know what the auther wanted to put, but probably should correct it so it's not worng.

**Comment by kristoff-it** [comment]
go has panic and recover, that's pretty much what exceptions are and it's even used by the json parser in go's stdlib to drive the logic.
