### ISSUE TITLE
Struct example typo?

### ISSUE THREAD

**Issue by ephetic** [ziglang/www.ziglang.org#21]
In the struct example: 
```
fn setYBasedOnX(x: *f32, y: f32) void {
    const point = @fieldParentPtr(Point, "x", x);
    point.y = y;
}
```
is it supposed to be `point.y = x;`?

**Comment by tiehuis** [comment]
This is example is correct. This is demonstrating how to retrieve the parent struct given only a pointer to a specific field within that struct. See that `x` is passed as a pointer in this case.

[Here](https://ziglang.org/documentation/master/#fieldParentPtr) is the signature for `@fieldParentPtr`.
