### ISSUE TITLE
[autodoc] data.js served without compression, wasting ~22MB of bandwidth

### ISSUE THREAD

**Issue by Ristovski** [ziglang/www.ziglang.org#214]
It appears that `data.js` does not get compressed like the other assets:

`main.js`:
`curl -sILH 'Accept-Encoding: gzip,deflate,br'  https://ziglang.org/documentation/master/std/main.js` -> `content-encoding: gzip`, looks good

`data.js`:
`curl -sILH 'Accept-Encoding: gzip,deflate,br'  https://ziglang.org/documentation/master/std/data.js` -> no `content-encoding` header present, gets sent uncompressed.

The file size of `data.js` is **23.9MB**, after gzipping its size is reduced down to **_1.9MB_**

**Comment by kristoff-it** [comment]
new autodoc implementation doesn't precompute the data anymore, closing
