### ISSUE TITLE
Support toggle dark mode and light mode

### ISSUE THREAD

**Issue by tisonkun** [ziglang/www.ziglang.org#216]
It seems now the mode always follows system settings. While I set the system preference as dark mode, I'd prefer to view the page in light mode.

**Comment by tisonkun** [comment]
@andrewrk I see this issue is closed as completed, but how to? I don't find a widget.

It's OK if you don't want to make the change, though.

**Comment by andrewrk** [comment]
I'm vetoing the change.

**Comment by tisonkun** [comment]
@andrewrk Thanks for your explanation. Do you think it's a bad idea or just don't want to spend time on it? If it's OK to have I may try to write a widget and the page can be still read offline.

**Comment by tisonkun** [comment]
FWIW - I download the page and remove the whole `@media (prefers-color-scheme: dark)` section to read offline and it works for me :)
