### ISSUE TITLE
Table of Content doesn't link locally

### ISSUE THREAD

**Issue by tisonkun** [ziglang/www.ziglang.org#217]
Even if I download the page and click the hyperlink on the ToC, it redirects me to the section on https://ziglang.org/documentation/.

I suppose these links should work offline, i.e., link to the sections of some page locally.

**Comment by tisonkun** [comment]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/18818196/190319784-ba410805-190b-43eb-9443-8cb483ed3b3c.png">

**Comment by kristoff-it** [comment]
modern langref definitely has local links, old one probably did too, the link preview at the bottom doesn't show verbatim what's in the HTML and instead resolves the link fully before showing it.
