### ISSUE TITLE
Add information or link about/to licenses of logos and mascots

### ISSUE THREAD

**Issue by musaprg** [ziglang/www.ziglang.org#219]
Currently, the website doesn't have any information related to the license notices of Zig's logo and mascots. GitHub repo manages them, but it is a bit difficult to find them. It would be more helpful to add that information for speakers who want to use them on their slide decks.

ref: https://github.com/ziglang/logo

**Comment by kristoff-it** [comment]
I'm not sure where we should put that information in a way that is both more accessible than being on the repo, and not too front and center since it's way less important that the other things on the front page. I'm happy to listen to your suggestions, if you have any.

**Comment by musaprg** [comment]
IMO, under the [Learn page](https://ziglang.org/learn/) is a relevant place to live. Putting a link to the repo there would be reasonable since it makes that repo accessible but not too front.
