### ISSUE TITLE
"get started" button does not stand out

### ISSUE THREAD

**Issue by Anton-4** [ziglang/www.ziglang.org#220]
I've been to the zig website a lot but today was the first time I've noticed the "GET STARTED" button.
I would say this is because it has the same background as the header and so it does not stand out.
Important buttons/information is also usually not located in the top right corner.

I'd recommend giving the "get started" button some "zig yellow" and putting it closer to the center of the screen (vertically and horizontally). [The squint test](https://www.learnui.design/blog/squint-test-ui-design-case-study.html) is often used to check if the important stuff stands out.

I hope this is helpful, thanks for working on zig :heart:

**Comment by kristoff-it** [comment]
Thank you for sharing your opinion. I think your point is fair. I remember discussing this idea (ie making the button stand out more) and we ended up settling for a "less aggressive" button color. 

I don't remember all the details from those discussions, but I'm also open to revisiting the idea, just not now.

I'll keep the issue open as a reminder and when the time comes I'll post here if we plan to make any change.

Thank you again & sorry for not being able to give you a definitive answer right away.

**Comment by Anton-4** [comment]
All good, no problem :)
