### ISSUE TITLE
An error with the `--single-threaded` option on build

### ISSUE THREAD

**Issue by ohno418** [ziglang/www.ziglang.org#229]
In [the "Zig competes with C instead of depending on it" section on the "In-depth Overview" page](https://ziglang.org/learn/overview/#zig-competes-with-c-instead-of-depending-on-it), the following command causes an error:

```
$ zig build-exe hello.zig -O ReleaseSmall --strip --single-threaded
error: unrecognized parameter: '--single-threaded'
```

I'm new to ziglang and not sure if I'm missing something, so just reporting.

version:

```
$ zig version --help
0.9.1
```

**Comment by kristoff-it** [comment]
fixed at some point in the past, the new flag is `-fsingle-threaded`
