### ISSUE TITLE
0.3.0 Documentation - Table Of Operators "Address of" shows `&amp;a`

### ISSUE THREAD

**Issue by euantorano** [ziglang/www.ziglang.org#23]
The [Table of operators](https://ziglang.org/documentation/0.3.0/#Table-Of-Operators) in the Zig 0.3.0 documentation shows the `Address of` operator as being [`&amp;a`](https://github.com/ziglang/www.ziglang.org/blob/master/www/documentation/0.3.0/index.html#L1732).

The [`langref.html.in` in the main repository](https://github.com/ziglang/zig/blob/master/doc/langref.html.in#L1357) looks correct as far as I can tell, so I'm not sure what's causing the `&` entity to be double escaped.

**Comment by andrewrk** [comment]
Thanks for the report! Inside the `{#syntax#}{#endsyntax#}` blocks, which are zig's markup on top of html, no escaping is needed. I'll fix this right away (but only in master branch, 0.3.0 docs will have this mistake forever)

**Comment by andrewrk** [comment]
Fixed in https://github.com/ziglang/zig/commit/c81a4b3e3d75577b69f37f57a21d2434019fa41d

There were a couple other instances of this problem, also fixed.
