### ISSUE TITLE
Missing download link for zig 0.10.1 on FreeBSD

### ISSUE THREAD

**Issue by SimonAdameit** [ziglang/www.ziglang.org#231]
The FreeBSD version is not listed for [0.10.1 downloads](https://ziglang.org/download/), but it was listed before e.g. for 0.10.0. The [support table](https://ziglang.org/download/0.10.1/release-notes.html#Support-Table) does not show any changes from 0.10.0.

The [direct link](https://ziglang.org/download/0.10.1/zig-freebsd-x86_64-0.10.1.tar.xz) works, so I suppose this is an oversight?

**Comment by andrewrk** [comment]
Thanks, I'm working on this now.

**Comment by andrewrk** [comment]
Fixed in d70966c99a12bf19fb50d4bec1d1e33c4ea276bf
