### ISSUE TITLE
Documentation: Clarification for pointer dereference and address of from Operators section

### ISSUE THREAD

**Issue by ghost** [ziglang/www.ziglang.org#234]
The examples shown in https://ziglang.org/documentation/master/#toc-Operators confused me...

![image](https://user-images.githubusercontent.com/1777466/219957325-62569503-1389-4823-b092-4b6139dc4ba4.png)

Cannot see any difference between them.

Is it a typo or is the way it's supposed to be?

**Comment by kristoff-it** [comment]
Both examples are showing both operators, so the same example applies to both.
