### ISSUE TITLE
Website is failing due to deprecated JSON TokenStream type

### ISSUE THREAD

**Issue by RossComputerGuy** [ziglang/www.ziglang.org#249]
CI run related: https://github.com/ziglang/www.ziglang.org/actions/runs/4997603372/jobs/8952133082

This has been happening for the past few days now, I tried looking into this myself so I could PR but couldn't find the relevant code. The closest I can find is [this](https://github.com/RossComputerGuy/zig-doctest/blob/main/src/doctest/test.zig#L17).

**Comment by kristoff-it** [comment]
Thanks, we're aware, we're just debating about how to fix the front page code snippet, we should come to some kind of conclusion by today.
