### ISSUE TITLE
Document how to install Zig

### ISSUE THREAD

**Issue by perillo** [ziglang/www.ziglang.org#253]
Currently there is no documentation about how to install Zig.

An example is https://go.dev/doc/install, where there are simple instructions for Linux, Mac and Windows.

**Comment by Azizadx** [comment]
there is [actually](https://github.com/ziglang/zig/wiki) although it might not be as great as the one you suggested but is good start

**Comment by kristoff-it** [comment]
https://ziglang.org/learn/getting-started/
