### ISSUE TITLE
remove unused files

### ISSUE THREAD

**Issue by r00ster91** [ziglang/www.ziglang.org#262]
https://github.com/ziglang/www.ziglang.org/commit/6a8419bcd7a99666270a64376f76a441c3a6a2bd added unused garbage files to the repo presumably unintentionally. CC @kristoff-it

**Comment by kristoff-it** [comment]
thanks fixed

**Comment by r00ster91** [comment]
I can still see `zero copy.svg` and `ziggy copy.svg` in `static/`.
