### ISSUE TITLE
Zig source code example in https://ziglang.org/ shows multi objects being iterated in a for

### ISSUE THREAD

**Issue by abner** [ziglang/www.ziglang.org#266]
Currently, Zig source code example in https://ziglang.org/ shows multi objects being iterated in a for, but it is a feature
not available in the last stable zig release version `0.10.1` (as today 2 July 2023) which is some way misleading as there is no information about that in the website.

```zig
 for (expected, list.items) |exp, actual| {
      try std.testing.expectEqual(exp, actual);
  }
```

Either it would be added a tip section under the code sample informing about that or have a sample code which would compile fine in the latest stable version of zig, I believe.

**Comment by kristoff-it** [comment]
The website tracks master branch, stable releases get stale very quickly with the pace of development. We do recommend to install an unstable build of Zig in the getting started section.
