### ISSUE TITLE
Tiny logo

### ISSUE THREAD

**Issue by jayschwa** [ziglang/www.ziglang.org#27]
Inspired by https://github.com/edent/SuperTinyIcons, I made a hand-written SVG of the Zig logo that is ~600 bytes. This should make it suitable for embedding in the language reference documentation, etc. Using an SVG optimizer, pushes it down to ~500 bytes, but it's not easy to tweak in that form. For comparison, the current logo is ~3.8 KB.

While it's not a pixel-perfect recreation of the original logo, it is intended to look the same at a cursory glance. Changes:
- Omitted text since it can be replaced with markup.
- Slightly reduced the aspect ratio to 3:2.

If there is interest in using this logo, I will start a PR that incorporates it into the website and documentation.

---

Current logo (rasterized):
![image](https://user-images.githubusercontent.com/475017/50059416-7a2a8b80-0154-11e9-9c51-caa635e1f2c7.png)

Tiny logo (rasterized):
![image](https://user-images.githubusercontent.com/475017/50059407-60894400-0154-11e9-8b46-14467d9f1caf.png)

SVG source: https://gist.github.com/jayschwa/1ef7b11ae2e82e78d3ac434140113a2d

**Comment by andrewrk** [comment]
Hey this is great! Thanks! I would take you up on your offer to move forward with using this.

I like the tweakable 600 byte one.
