### ISSUE TITLE
feature request : https://ziglang.org/download/ - SHA hashes 

### ISSUE THREAD

**Issue by shishini** [ziglang/www.ziglang.org#290]
Is it possible to add a text file in the download page that have the SHA256 or SH512 hashes for the downloads
I understand the downloads are signed 

But a SH256 , for many will make it easier to verify the downloads

**Comment by nektro** [comment]
https://ziglang.org/download/index.json has them already

**Comment by shishini** [comment]
great, didnt think to look in this file
then maybe the feature request can become, add a SHA colum next to the size column

**Comment by andrewrk** [comment]
the verification method offered is minisign, not SHA. related: #243
