### ISSUE TITLE
source download filesize regression

### ISSUE THREAD

**Issue by tiehuis** [ziglang/www.ziglang.org#291]
See https://ziglang.org/download/.

```
zig-0.11.0.tar.xz	minisig	Source	62.1MiB
zig-0.10.1.tar.xz	minisig	Source	14.4MiB
```

---

![2023-08-14-164408_321x158_scrot](https://github.com/ziglang/www.ziglang.org/assets/4605603/b990d250-7987-44d5-bd18-60bcd38143bc)

There is a `zig-cache` folder that isn't correctly cleared. This was made visible in https://github.com/ziglang/www.ziglang.org/commit/7830fe5eca63dc99a97ca0b78b04a49a60961c58 however the root issue is that the working environment on the CI server is not correctly cleared. This would have been last been created in https://github.com/ziglang/zig/commit/a3552a6c5083a4a58223b38bc20df4ada0c736c1 but is no longer created.

Should be sufficient to just clear the server working directory. May be worth explicitly clearing the build artefacts as in the previous implementation or at least adding a guard to check the working directory is clean (`git status --porcelain`).

**Comment by andrewrk** [comment]
oof, sorry about that.

**Comment by andrewrk** [comment]
it looks like I intended to use `git archive` to create the tar.xz file, but I didn't actually remove the manual `tar` command. plus there is that extra tar command for bootstrap. goodness

**Comment by andrewrk** [comment]
I'll give it a day until the fix makes its way into the master branch tarballs, then I'll go update the 0.11.0 source tarballs.
