### ISSUE TITLE
Fix compiling C Source code section for 0.11 docs

### ISSUE THREAD

**Issue by courajs** [ziglang/www.ziglang.org#296]
This is correct for the master documentation, but out of date in the 0.11 docs.

https://ziglang.org/documentation/0.11.0/#Compiling-C-Source-Code
vs
https://ziglang.org/documentation/master/#Compiling-C-Source-Code

```zig
lib.addCSourceFile("src/lib.c", &[_][]const u8{
    "-Wall",
    "-Wextra",
    "-Werror",
});
```
vs
```zig
lib.addCSourceFile(.{ .file = .{ .path = "src/lib.c" }, .flags = &.{
        "-Wall",
        "-Wextra",
        "-Werror",
    } });
```

The other zig build system sections are correct.
Can we back-port this docs change to 0.11?

**Comment by kristoff-it** [comment]
closing since 0.11 is old now
