### ISSUE TITLE
Zig & OOP - almost nothing definitive written anywhere.

### ISSUE THREAD

**Issue by paul-hammant** [ziglang/www.ziglang.org#30]
Contrast https://www.google.com/search?&q=oop+in+rust
and https://www.google.com/search?&q=oop+in+zip.

This site needs a page/section that says "no OOP support yet" IMO

**Comment by andrewrk** [comment]
Here's an issue you can subscribe to: https://github.com/ziglang/zig/issues/130

But I disagree with the premise that OOP is a sort of "default" for a programming language and therefore has to be explicitly addressed, so I'm closing the issue.
