### ISSUE TITLE
Wrong fact in the "Why Zig When There is Already C++, D, and Rust?" article

### ISSUE THREAD

**Issue by grafov** [ziglang/www.ziglang.org#320]
There is wrong statement:
> C++, D, and Go have throw/catch exceptions

In content/learn/why_zig_rust_d_cpp.en.md.

Really Go language have no trow/catch exceptions. Check the language spec https://go.dev/ref/spec

Please remove this statement about Go language. fix the source in English and translations. Zig good enough and wrong facts about other languages don't do it better.

**Comment by andrewrk** [comment]
Panic and recover is throw and catch exceptions.
