### ISSUE TITLE
Spelling mistake in the build.zig.zon example file

### ISSUE THREAD

**Issue by KellanHiggins** [ziglang/www.ziglang.org#322]
In build.zig.zon, "ensure" is spelled "insure" in the example documentation.

I know not a big deal, but we aren't protecting it against theft or loss! :P.

Line 51.

**Comment by kristoff-it** [comment]
I'm having trouble finding the location where this occurs. Can you give me a link to the page you're referring to?

**Comment by nektro** [comment]
https://github.com/ziglang/zig/blob/1e42a3de89e8a4e78b76d8fc5192bbacf842c02b/lib/init/build.zig.zon#L51

**Comment by kristoff-it** [comment]
The example build.zig.zon has now differend wording that doesn't contain the typo anymore.
