### ISSUE TITLE
Putting 0.12 Release above master on the download page

### ISSUE THREAD

**Issue by horenso** [ziglang/www.ziglang.org#352]
In the [Zig Roadmap Video on Youtube](https://www.youtube.com/watch?v=5eL_LcxwwHg) at 18:40 Andrews says:

> The idea is that people should be able to pin 0.12

As I understood from the video, it is now recommended to stick with the releases instead of following the latest master. If my impression is correct, it'd be a good change to put the latest release 0.12.0 on top of the [Download Page](https://ziglang.org/download/). The master download section should also be styled differently. If you go to blender.org, it also has the latest release at the top and then a red section with "Go experimental".

I recommend:

1. Latest release
2. Lasted master build
3. Older versions

If that's a welcome change I'd be willing to help out too ;)

**Comment by andrewrk** [comment]
Thanks for the suggestion but they're not sorted by recommended order - they're sorted by date.
