### ISSUE TITLE
Zig Standard library documentation in 0.12 language reference linking to master

### ISSUE THREAD

**Issue by timsavage** [ziglang/www.ziglang.org#355]
The link to the Zig Standard Library from the language reference is linking to master instead of 0.12

Is currently:
> `The <a href="https://ziglang.org/documentation/master/std/">Zig Standard Library</a> has its own documentation.> `

Would expect
> `The <a href="https://ziglang.org/documentation/0.12.0/std/">Zig Standard Library</a> has its own documentation.`

Link to location in the documentation source:
https://github.com/ziglang/www.ziglang.org/blob/master/content/documentation/0.12.0/index.html#L784

**Comment by timsavage** [comment]
The behavior appears to be consistent across all language reference versions.

**Comment by Atomk** [comment]
This is not fixed apparently, an example: https://ziglang.org/documentation/0.13.0/#Zig-Standard-Library
(the "Zig Standard Library" link points to the documentation for `master` instead of  `0.13.0`, this happens in all other versions)
