### ISSUE TITLE
Mark current stable release in download.json

### ISSUE THREAD

**Issue by AMythicDev** [ziglang/www.ziglang.org#357]
I am writing a version manager for Zig called `zigvm` and 
currently it can install releases from semver or `master`. Additionally I would also like to be able to install the latest stable release with it by saying something like `zigvm install stable`.

My current approach to this would be to loop over the semver and compare them till I find the greatest of them. But I find this more more of a naive and slow solution. I thing if the `download.json` can describe the current stable release by something like `"stable": true` or `"tags": ["stable"]` or maybe a separate entry like `stable` that would basically be an alias to the current stable release, we can avoid all the comparisons an simply check which release has the stable tag.

**Comment by nektro** [comment]
in practice it's always the second entry in the file

**Comment by AMythicDev** [comment]
That's mostly because of how zig is being released. Let's say if there's a 0.11.1, will it be at the top or right right above 0.11.0 or where? I feel there are quite a many possibilities of failure by taking this assumption.

**Comment by andrewrk** [comment]
you have all the data you need with semantic versioning.

**Comment by AMythicDev** [comment]
@andrewrk just a side question, if there's a patch release, say `0.11.1` where will it be placed in the download.json file? Will it be right under `master` like where 0.12.0 is right now or will be somewhere adjacent to 0.11.0?

**Comment by andrewrk** [comment]
JSON object keys are not ordered.

**Comment by AMythicDev** [comment]
Thanks, I am going with the semantic version analysis method.
