### ISSUE TITLE
Typo: a small typo in the Russian version of the documentation

### ISSUE THREAD

**Issue by Refffy** [ziglang/www.ziglang.org#369]
I started learning Zig recently and found a small typo in the part about comparing  Zig with C++, Rust, and D in Russian documentation.

**Description:**
In [this place](https://github.com/ziglang/www.ziglang.org/blob/master/content/learn/why_zig_rust_d_cpp.ru.md?plain=1#L94) of Russian documentation, there is a typo involving the word "стать". Instead of "может стать изменить ситуацию", it should be "может изменить ситуацию".

**Proposed Fix:**
Replace the phrase with "может изменить ситуацию".

This correction will improve clarity and correctness in the documentation.

**Comment by kristoff-it** [comment]
Please send a PR for changes to a localization.
