### ISSUE TITLE
Re-design home (landing) page

### ISSUE THREAD

**Issue by ajTronic** [ziglang/www.ziglang.org#378]
The [home page](https://ziglang.org) needs a better look in my opinion. A lot of people judge a book by it's cover, and re-designing the home page would make more people be able appreciate the beauty of Zig, and make it seem more professional. 

For example, https://c3-lang.org/ has an excellent landing page. So does https://react.dev/. 

Let me know what you think. I'd be happy to create a PR to re-style it.

**Comment by andrewrk** [comment]
no thank you
