### ISSUE TITLE
Devlog and title in rss feed

### ISSUE THREAD

**Issue by painhardcore** [ziglang/www.ziglang.org#395]
Hi! I noticed that the RSS feed for the devlog currently uses just the date as the title, even though a proper title is available in the description.

Could you update the RSS feed to use the actual title where it's available, instead of just an ID?

**Comment by kristoff-it** [comment]
I needed to add a new feature to Zine to make this work. It now added to v0.6.3 so you should start seeing the correct title also in the RSS feed going forward.
