### ISSUE TITLE
I searched for anonymous function (and lambda function) in the docs and didn't find it

### ISSUE THREAD

**Issue by danr** [ziglang/www.ziglang.org#40]
Anonymous functions (lambda functions) seem either to be missing for the docs or the language ;)

**Comment by tmccombs** [comment]
I could be wrong, but my impressions from the docs is that they aren't in the language. But given that most modern languages have some kind of closure/lambda, it would probably be good to explicitly state if zig doesn't have them, and why (or maybe there are plans to add them but it hasn't happened yet?).   At the very least  it seems like you should be able to statically define an anonymous function from a compile time function, similar to what you can do with a struct.

**Comment by gpanders** [comment]
Anonymous functions can be used by accessing an anonymous struct, e.g.:

```zig
struct {
    fn myfunc(x: u8, y: u8) u8 {
        return x + y;
    }
}.myfunc
```

This is not documented anywhere but you can find examples of it in the standard library.

**Comment by kristoff-it** [comment]
Closures are not in the language but they are being discussed in https://github.com/ziglang/zig/issues/229

Closing until that gets resolved
