### ISSUE TITLE
Move index on pages to the side for easier navigation

### ISSUE THREAD

**Issue by mindspyke** [ziglang/www.ziglang.org#44]
Consider moving the "index" sections on your website to the side. 

- This prevents users from having to scroll down to get to some content, or back up again to look at the index.
- It's 2019 and most users have a monitor with a width of more than 1024 pixels, so maybe make some more use of that horizontal screen real estate. 
- Other language docs like Rust also have their index/navigation moved to the side.

**Comment by kristoff-it** [comment]
This was done since version 0.6.0 of the docs, thanks for the report!
