### ISSUE TITLE
I searched for variadic function in the docs and didn't find it

### ISSUE THREAD

**Issue by tmccombs** [ziglang/www.ziglang.org#46]
I know it supports variadic functions, since it is in several declarations. But it isn't clear how to use it, or what the type of the variadic argument is.

**Comment by kristoff-it** [comment]
Since then we now don't have variadic functions anymore, but we do instead have tuples. Please open another issue if you think we should improve that part of the documentation

**Comment by tmccombs** [comment]
Huh. Is it possible to call a C variadic function (such as printf)?

**Comment by kristoff-it** [comment]
Sorry I assumed you meant Zig variadic functions. Yes you can call C varargs functions (the calling code looks just like a normal function call), while exposing a vararg API to C is not trivially possible through the language, but it is possible to use inline assembly to do it. @suirad is working on a userspace implementation of this feature.
