### ISSUE TITLE
hello world doesn't compile

### ISSUE THREAD

**Issue by witaly-iwanow** [ziglang/www.ziglang.org#49]
The very first example does not compile, kind of. The problem is google takes you to the master doc while you have to use the one corresponding to the version installed (ziglang.org/documentation/0.5.0/ in my case).
I think that first semi-advanced Hello World with stdout manipulations should be removed completely - at this point the person reading it just wants to print "Hello, world!" in as little code as possible, and getting "error: type 'std.os.windows.GetStdHandleError!std.fs.file.File' does not support field access" on Hello World is not exactly reassuring

**Comment by andrewrk** [comment]
![Screenshot_2019-11-30_21-52-32](https://user-images.githubusercontent.com/106511/69908638-cbf71080-13bb-11ea-90a2-0f1d2c54df32.png)

**Comment by witaly-iwanow** [comment]
I figured that out already (second sentence). My point is that first Hello World should be removed completely

**Comment by witaly-iwanow** [comment]
Hello World using some advanced API which changes between releases? Really?
