### ISSUE TITLE
Add support for RSS

### ISSUE THREAD

**Issue by witling** [ziglang/www.ziglang.org#50]
I've been looking for the RSS feed of zig updates for quite some time now and I cannot seem to find it. Subscribing to RSS for me is way more convenient than fetching the json file as it integrates better with aggregators. I therefore propose to:

- add a file complying with the RSS protocol to the website
- add changelog to said feed

**Comment by andrewrk** [comment]
what changelog?

**Comment by witling** [comment]
I mean a slim version of [release notes](https://ziglang.org/download/0.5.0/release-notes.html).

**Comment by purringChaos** [comment]
https://github.com/ziglang/www.ziglang.org/commits.atom might work.
or also https://github.com/ziglang/zig/releases.atom

**Comment by kassane** [comment]
There was a feed missing for news posts on the site.

**Comment by nektro** [comment]
https://ziglang.org/news/index.xml this issue can be closed now
