### ISSUE TITLE
Fix responsiveness

### ISSUE THREAD

**Issue by OverMighty** [ziglang/www.ziglang.org#54]
The website does not scale properly on mobile devices. The [HTML `viewport` meta tag](https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag) should be used to set the viewport's width to the width of the device's screen and to set the correct initial zoom level when pages load:

```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

Before adding the meta tag:

https://user-images.githubusercontent.com/33205782/77707044-4e878980-6fc4-11ea-94ae-dc2226f98bf3.jpg
https://user-images.githubusercontent.com/33205782/77707052-52b3a700-6fc4-11ea-9ea7-0ce77606d691.jpg

After adding the meta tag:

https://user-images.githubusercontent.com/33205782/77707031-4891a880-6fc4-11ea-9e23-f25cd0813446.jpg
https://user-images.githubusercontent.com/33205782/77707036-4b8c9900-6fc4-11ea-9bad-d1d6e07684da.jpg

However, with the current CSS, tables that are too broad are not clipped to fit into their padding box:

https://user-images.githubusercontent.com/33205782/77707042-4d565c80-6fc4-11ea-8d81-db73bde6917e.jpg

The following CSS code fixes this problem:

```css
table {
    display: block;
    overflow: auto;
}
```

When a table overflows, it will be clipped to fit into its padding box and it will become scrollable:

https://user-images.githubusercontent.com/33205782/77707027-462f4e80-6fc4-11ea-951c-7acb9284ea14.jpg

**Comment by jayschwa** [comment]
Related history:
- Pull request #43 
- Commit dddd55c

**Comment by OverMighty** [comment]
I just want to fix scaling on mobile devices, I don't want to add`user-scalable=no`. In fact, I think it hurts accessibility, and I turn on "Force enable zoom" in the settings of Chromium-based browsers for Android.

Now,
> If a mobile device can't figure out how to render a simple text document [...], that's the device's fault, not the web page.

See https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag:
> Narrow screen devices (e.g. mobiles) render pages in a virtual window or viewport, which is usually wider than the screen, and then shrink the rendered result down so it can all be seen at once. Users can then pan and zoom to see different areas of the page. For example, if a mobile screen has a width of 640px, pages might be rendered with a virtual viewport of 980px, and then it will be shrunk down to fit into the 640px space.

If all web browsers behave like this and fixing scaling on mobile devices only takes a single line of HTML (which, if you use Visual Studio Code, is even generated for you when creating an empty HTML5 document using the `html:5` Emmet abbreviation), I'd say it *is* your website's fault for not displaying properly on all devices.

Also, it would be great if Andrew could clarify what he meant by "it looked weird on my phone."

**Comment by kristoff-it** [comment]
I added this a while ago, the new redesign will take responsiveness in consideration. Thanks for the report.
