### ISSUE TITLE
Spammy link in "Reading and Viewing Material"

### ISSUE THREAD

**Issue by anand-bala** [ziglang/www.ziglang.org#63]
It looks like the following link redirects to some spam-like, tracker website and the actual endpoint doesn't exist anymore.
```
2019-02-11 - Moving to Zig for ARM Development
```

**Comment by deingithub** [comment]
The article remains available at the Web Archive (http://web.archive.org/web/20190212180126/http://www.sjdh.us/2019/02/11/continuing-with-zig.html/) and makes still-valid points, so re-including the archive link might be desirable?
