### ISSUE TITLE
Make site more welcoming to newcomers

### ISSUE THREAD

**Issue by SuperAuguste** [ziglang/www.ziglang.org#66]
Currently, the website is rather unwelcoming to newcomers. When you land on the homepage, there are no code examples that could demonstrate Zig's capabilities, and beginner-friendly resources other than the official documentation are sparse and not directly linked on the website.

[Nim's homepage](https://nim-lang.org/) and [Go's homepage](https://golang.org/) come to mind as examples that could be used to improve Zig's homepage.

**Comment by andrewrk** [comment]
> no code examples

??

**Comment by SuperAuguste** [comment]
Miscommunication on my part. There are indeed code examples, but they are not directly visible or runnable. I simply believe that the empty space at the top of the homepage could be used to show all of the examples in action.

**Comment by SuperAuguste** [comment]
Super shoddy and quickly photoshopped together concept art of what I'm trying to communicate:
![image](https://user-images.githubusercontent.com/19855629/80895184-17d21c80-8cb0-11ea-95de-3a557e85d733.png)

**Comment by andrewrk** [comment]
I see what you're going for here. It's worth considering. How about we revisit this topic when we have an online playground for running zig code? Which, by the way, I am insisting must run client side in WASM with no server component.

**Comment by SuperAuguste** [comment]
That sounds great! I'll close this issue and reopen it when it's viable!
