### ISSUE TITLE
Go as wrong example of languages with exceptions

### ISSUE THREAD

**Issue by sj14** [ziglang/www.ziglang.org#69]
As a Go user who is interested in Zig, I came across this sentence on the homepage:

> C++, D, and Go have throw/catch exceptions, so foo() might throw an exception, and prevent bar() from being called.

Go does not have exceptions. Quote from their [blog](https://blog.golang.org/error-handling-and-go):

> The language's design and conventions encourage you to explicitly check for errors where they occur (as distinct from the convention in other languages of throwing exceptions and sometimes catching them).

Thus, I would suggest to remove Go from the list of examples. 
✌️

**Comment by andrewrk** [comment]
It does have exceptions, in the form of panic and recover: https://blog.golang.org/defer-panic-and-recover
