### ISSUE TITLE
sine.zig example fails to compile with "error: extern functions have no body"

### ISSUE THREAD

**Issue by shybyte** [ziglang/www.ziglang.org#70]
When I try to compile the sine.zig example from https://ziglang.org/#Integration-with-C-libraries-without-FFIbindings using `zig build-exe sine.zig -lsoundio -lc`, I get the error message:

```
./sine.zig:27:1: error: extern functions have no body
extern fn write_callback(
```

**Comment by Vexu** [comment]
`extern` as a calling convention was replaced with `callconv(.C)`.
