### ISSUE TITLE
Documentation is deprecated for options of compliler optimizations

### ISSUE THREAD

**Issue by dedifferentiator** [ziglang/www.ziglang.org#75]
Zig version: `0.6.0+53c63bdb7` on `Linux 5.8.14-arch1-1`

https://ziglang.org/documentation/master/#ReleaseFast

Looks like `--release-fast` `--release-safe` `--release-small` were options in the past, but now they are replaced with `-O [mode]` where `[mode]` is `Debug` | `ReleaseFast` | `ReleaseSafe` | `ReleaseSmall`. Although I haven't found since which version they were replaced (if they were).

```
$ zig test --help
  ...
  -O [mode]                 Choose what to optimize for
    Debug                   (default) Optimizations off, safety on
    ReleaseFast             Optimizations on, safety off
    ReleaseSafe             Optimizations on, safety on
    ReleaseSmall            Optimize for small binary, safety off
  ...
```

Example:
`zig test main-testing.zig --release-fast` returns `error: unrecognized parameter: '--release-fast'`
`zig test main-testing.zig -O ReleaseFast` seems to work as intended.

**Comment by kristoff-it** [comment]
Thank you for the report, this seems to have been fixed in the meantime. If I missed something, feel free to open another issue.
