### ISSUE TITLE
Conflicting release note text about version 0.7.1

### ISSUE THREAD

**Issue by awulkan** [ziglang/www.ziglang.org#77]
[Here](https://ziglang.org/download/0.7.0/release-notes.html#These-Release-Notes-are-Incomplete) it says:

> My plan is to do a 0.7.1 bug fix release in 1-3 weeks

But [here](https://ziglang.org/download/0.7.0/release-notes.html#This-Release-Contains-Bugs) it says:

> It is unlikely there will be a 0.7.1, however it is planned there will be a 0.8.1.

**Comment by andrewrk** [comment]
Oops sorry about that. Correct text is the former. I will fix it momentarily
