### ISSUE TITLE
"Get Started" button always navigate to english version page

### ISSUE THREAD

**Issue by codehz** [ziglang/www.ziglang.org#97]
I'm trying to add new [translation](#95) for www.ziglang.org, but I found the Get Started button is always lead me to the English version of the page.
I am not familiar with hugo, I don’t know how to implement language redirection..

**Comment by kristoff-it** [comment]
Hi @codehz, I just pushed a change that now allows you to specify the language version of getting-started.md you want to link to. I'm not immediately defaulting to the current language to allow people to work on a getting-started translation in a second moment and link to the english version momentarily, which also happens to be the current state of the Italian translation made by me :)

Here's how to do it:

```
{{< slogan get_started="INIZIA QUI" docs="Documentazione" notes="Note" lang="it">}}
...
```

**Comment by codehz** [comment]
Thanks, I think it is working
